services:

  lake_db:
    image: postgres:17
    environment:
      POSTGRES_DB: lake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - lake_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse_db:
    image: postgres:17
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow_db:
    image: postgres:17
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.0
    depends_on:
      airflow_db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      _PIP_ADDITIONAL_REQUIREMENTS: "python-dotenv psycopg2-binary requests dlt[postgres] dbt-core==1.7.19 dbt-postgres==1.7.19"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Admin"
      _AIRFLOW_WWW_USER_LASTNAME: "User"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
      _AIRFLOW_WWW_USER_ROLE: "Admin"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extractor:/opt/airflow/extractor
      - ./dlt_project:/opt/airflow/dlt_project
      - ./dbt_project:/opt/airflow/dbt_project
      - ./logs:/opt/airflow/logs
    entrypoint: /bin/bash
    command:
      - -c
      - airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true

  airflow-webserver:
    image: apache/airflow:2.9.0
    depends_on:
      airflow_db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      lake_db:
        condition: service_healthy
      warehouse_db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      _PIP_ADDITIONAL_REQUIREMENTS: "python-dotenv psycopg2-binary requests dlt[postgres] dbt-core==1.7.19 dbt-postgres==1.7.19"
      ERP_API_KEY: ${ERP_API_KEY}
      ERP_BASE_URL: ${ERP_BASE_URL}
      LAKE_DB_HOST: lake_db
      LAKE_DB_PORT: "5432"
      LAKE_DB_NAME: lake
      LAKE_DB_USER: postgres
      LAKE_DB_PASSWORD: postgres123
      WAREHOUSE_DB_HOST: warehouse_db
      WAREHOUSE_DB_PORT: "5432"
      WAREHOUSE_DB_NAME: warehouse_db
      WAREHOUSE_DB_USER: postgres
      WAREHOUSE_DB_PASSWORD: postgres123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extractor:/opt/airflow/extractor
      - ./dlt_project:/opt/airflow/dlt_project
      - ./dbt_project:/opt/airflow/dbt_project
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.0
    depends_on:
      airflow_db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      lake_db:
        condition: service_healthy
      warehouse_db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      _PIP_ADDITIONAL_REQUIREMENTS: "python-dotenv psycopg2-binary requests dlt[postgres] dbt-core==1.7.19 dbt-postgres==1.7.19"
      ERP_API_KEY: ${ERP_API_KEY}
      ERP_BASE_URL: ${ERP_BASE_URL}
      LAKE_DB_HOST: lake_db
      LAKE_DB_PORT: "5432"
      LAKE_DB_NAME: lake
      LAKE_DB_USER: postgres
      LAKE_DB_PASSWORD: postgres123
      WAREHOUSE_DB_HOST: warehouse_db
      WAREHOUSE_DB_PORT: "5432"
      WAREHOUSE_DB_NAME: warehouse_db
      WAREHOUSE_DB_USER: postgres
      WAREHOUSE_DB_PASSWORD: postgres123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extractor:/opt/airflow/extractor
      - ./dlt_project:/opt/airflow/dlt_project
      - ./dbt_project:/opt/airflow/dbt_project
      - ./logs:/opt/airflow/logs
    command: scheduler

volumes:
  lake_data:
  warehouse_data:
  airflow_db_data:
